# 可参考 https://docs.min.io/docs/minio-docker-quickstart-guide.html
# 预览地址参考 https://oss.odboy.cn/blog/files/test.jpeg
version: '3'
services:
  minio:
    image: registry.cn-shanghai.aliyuncs.com/odboy/ops:minio-2024.05.28
    container_name: minio
    restart: unless-stopped
    volumes:
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
      MINIO_SECRET_KEY: "MINIO_SECRET_KEY"
      MINIO_SERVER_URL: https://oss.odboy.cn  # minio 9001端口对应的地址
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "9002:9000" # 文件上传&预览端口
      - "9001:9001" # 控制台访问端口
    # 配置内存
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
